export type VoiceProviderChannel = 'llm' | 'stt' | 'tts' | 'realtime'
export type VoiceProviderStatus = 'runtime' | 'pipecat' | 'inventory'

export interface VoiceProviderPreset {
  value: string
  label: string
  status: VoiceProviderStatus
  baseUrl: string
  model: string
  wireApi?: string
  realtimeVoice?: string
  realtimeTranscriptionModel?: string
  reuseTtsKey?: boolean
  note?: string
}

export const LLM_PROVIDER_PRESETS: VoiceProviderPreset[] = [
  {
    value: 'flowguide',
    label: 'FlowGuide gateway',
    status: 'runtime',
    baseUrl: 'https://ai.flowguide.cc',
    model: 'gpt-5.5',
    wireApi: 'responses',
  },
  {
    value: 'openai',
    label: 'OpenAI',
    status: 'runtime',
    baseUrl: 'https://api.openai.com/v1',
    model: 'gpt-4o-mini',
    wireApi: 'responses',
  },
  {
    value: 'openrouter',
    label: 'OpenRouter',
    status: 'runtime',
    baseUrl: 'https://openrouter.ai/api/v1',
    model: 'openai/gpt-4o-mini',
    wireApi: 'chat_completions',
  },
  {
    value: 'groq',
    label: 'Groq',
    status: 'runtime',
    baseUrl: 'https://api.groq.com/openai/v1',
    model: 'llama-3.3-70b-versatile',
    wireApi: 'chat_completions',
  },
  {
    value: 'mistral',
    label: 'Mistral',
    status: 'runtime',
    baseUrl: 'https://api.mistral.ai/v1',
    model: 'mistral-small-latest',
    wireApi: 'chat_completions',
  },
  {
    value: 'deepseek',
    label: 'DeepSeek',
    status: 'runtime',
    baseUrl: 'https://api.deepseek.com',
    model: 'deepseek-chat',
    wireApi: 'chat_completions',
  },
  {
    value: 'qwen',
    label: 'Qwen',
    status: 'runtime',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    model: 'qwen-plus',
    wireApi: 'chat_completions',
  },
  {
    value: 'volcengine',
    label: 'Volcengine Ark (Doubao)',
    status: 'runtime',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    model: 'doubao-seed-1-6-250615',
    wireApi: 'chat_completions',
  },
  {
    value: 'together',
    label: 'Together AI',
    status: 'runtime',
    baseUrl: 'https://api.together.xyz/v1',
    model: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    wireApi: 'chat_completions',
  },
  {
    value: 'perplexity',
    label: 'Perplexity',
    status: 'runtime',
    baseUrl: 'https://api.perplexity.ai',
    model: 'sonar',
    wireApi: 'chat_completions',
  },
  {
    value: 'xai',
    label: 'xAI',
    status: 'runtime',
    baseUrl: 'https://api.x.ai/v1',
    model: 'grok-3-mini',
    wireApi: 'chat_completions',
  },
  {
    value: 'ollama',
    label: 'Ollama',
    status: 'runtime',
    baseUrl: 'http://localhost:11434/v1',
    model: 'llama3.1',
    wireApi: 'chat_completions',
  },
  {
    value: 'cerebras',
    label: 'Cerebras',
    status: 'runtime',
    baseUrl: 'https://api.cerebras.ai/v1',
    model: 'llama3.1-8b',
    wireApi: 'chat_completions',
  },
  {
    value: 'anthropic',
    label: 'Anthropic',
    status: 'inventory',
    baseUrl: 'https://api.anthropic.com/v1',
    model: 'claude-sonnet-4-6',
    wireApi: 'chat_completions',
    note: 'Native Anthropic runtime adapter is not wired to this settings path yet.',
  },
  {
    value: 'google',
    label: 'Google Gemini',
    status: 'inventory',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    model: 'gemini-2.5-flash',
    wireApi: 'chat_completions',
  },
  {
    value: 'azure',
    label: 'Azure OpenAI',
    status: 'inventory',
    baseUrl: '',
    model: 'gpt-4o-mini',
    wireApi: 'chat_completions',
    note: 'Azure endpoints are resource and deployment specific.',
  },
  {
    value: 'aws',
    label: 'AWS Bedrock',
    status: 'inventory',
    baseUrl: '',
    model: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
    wireApi: 'chat_completions',
    note: 'Bedrock requires a region and native adapter.',
  },
]

export const TTS_PROVIDER_PRESETS: VoiceProviderPreset[] = [
  {
    value: 'openrouter',
    label: 'OpenRouter',
    status: 'runtime',
    baseUrl: 'https://openrouter.ai/api/v1',
    model: 'mistralai/voxtral-mini-tts-2603',
  },
  {
    value: 'minimax',
    label: 'MiniMax',
    status: 'runtime',
    baseUrl: 'https://api.minimax.chat',
    model: 'speech-2.8-hd',
  },
  {
    value: 'elevenlabs',
    label: 'ElevenLabs',
    status: 'runtime',
    baseUrl: 'https://api.elevenlabs.io',
    model: 'eleven_multilingual_v2',
  },
  {
    value: 'volcengine',
    label: 'Volcengine Doubao TTS',
    status: 'runtime',
    baseUrl: 'https://openspeech.bytedance.com/api/v3/tts/unidirectional',
    model: 'seed-tts-2.0',
    note: 'Uses Volcengine Speech native TTS with X-Api-Key and X-Api-Resource-Id headers.',
  },
  {
    value: 'openai',
    label: 'OpenAI',
    status: 'pipecat',
    baseUrl: 'https://api.openai.com/v1',
    model: 'gpt-4o-mini-tts',
    note: 'Wired through Pipecat realtime, not the turn-based TTS client.',
  },
  {
    value: 'azure',
    label: 'Azure Speech',
    status: 'inventory',
    baseUrl: '',
    model: 'azure-neural-voice',
    note: 'Azure Speech endpoints are resource and region specific.',
  },
  {
    value: 'aws',
    label: 'AWS Polly',
    status: 'inventory',
    baseUrl: '',
    model: 'neural',
    note: 'AWS Polly requires region-specific credentials.',
  },
  {
    value: 'cartesia',
    label: 'Cartesia',
    status: 'inventory',
    baseUrl: 'https://api.cartesia.ai',
    model: 'sonic-2',
  },
  {
    value: 'deepgram',
    label: 'Deepgram',
    status: 'inventory',
    baseUrl: 'https://api.deepgram.com/v1',
    model: 'aura-2-thalia-en',
  },
  {
    value: 'google',
    label: 'Google Cloud TTS',
    status: 'inventory',
    baseUrl: 'https://texttospeech.googleapis.com/v1',
    model: 'chirp3-hd',
  },
  {
    value: 'groq',
    label: 'Groq',
    status: 'inventory',
    baseUrl: 'https://api.groq.com/openai/v1',
    model: 'playai-tts',
  },
  {
    value: 'hume',
    label: 'Hume',
    status: 'inventory',
    baseUrl: 'https://api.hume.ai/v0',
    model: 'octave',
  },
  {
    value: 'lmnt',
    label: 'LMNT',
    status: 'inventory',
    baseUrl: 'https://api.lmnt.com/v1',
    model: 'aurora',
  },
  {
    value: 'rime',
    label: 'Rime',
    status: 'inventory',
    baseUrl: 'https://users.rime.ai/v1',
    model: 'mist',
  },
  {
    value: 'together',
    label: 'Together AI',
    status: 'inventory',
    baseUrl: 'https://api.together.xyz/v1',
    model: 'cartesia/sonic',
  },
  {
    value: 'xai',
    label: 'xAI',
    status: 'inventory',
    baseUrl: 'https://api.x.ai/v1',
    model: 'grok-tts',
  },
  {
    value: 'speechmatics',
    label: 'Speechmatics',
    status: 'inventory',
    baseUrl: 'https://mp.speechmatics.com/v1',
    model: 'flow',
  },
  {
    value: 'soniox',
    label: 'Soniox',
    status: 'inventory',
    baseUrl: 'https://api.soniox.com/v1',
    model: 'tts-default',
  },
]

export const STT_PROVIDER_PRESETS: VoiceProviderPreset[] = [
  {
    value: 'whisper',
    label: 'Whisper compatible',
    status: 'runtime',
    baseUrl: 'https://openrouter.ai/api/v1',
    model: 'openai/whisper-1',
    reuseTtsKey: true,
  },
  {
    value: 'openai',
    label: 'OpenAI Whisper',
    status: 'runtime',
    baseUrl: 'https://api.openai.com/v1',
    model: 'whisper-1',
    reuseTtsKey: false,
  },
  {
    value: 'minimax',
    label: 'MiniMax compatible',
    status: 'runtime',
    baseUrl: 'https://api.openai.com/v1',
    model: 'whisper-1',
    reuseTtsKey: false,
    note: 'Current adapter uses the OpenAI Whisper-compatible transcription API.',
  },
  {
    value: 'volcengine',
    label: 'Volcengine Doubao ASR',
    status: 'runtime',
    baseUrl: 'wss://openspeech.bytedance.com/api/v3/sauc/bigmodel',
    model: 'volc.bigasr.sauc.duration',
    reuseTtsKey: true,
    note: 'Can reuse the Volcengine Speech TTS key; browser recordings are normalized to 16 kHz PCM WAV before transcription.',
  },
  {
    value: 'deepgram',
    label: 'Deepgram',
    status: 'inventory',
    baseUrl: 'https://api.deepgram.com/v1',
    model: 'nova-3',
  },
  {
    value: 'assemblyai',
    label: 'AssemblyAI',
    status: 'inventory',
    baseUrl: 'https://api.assemblyai.com/v2',
    model: 'best',
  },
  {
    value: 'aws',
    label: 'AWS Transcribe',
    status: 'inventory',
    baseUrl: '',
    model: 'default',
    note: 'AWS Transcribe requires region-specific transport and credentials.',
  },
  {
    value: 'azure',
    label: 'Azure Speech',
    status: 'inventory',
    baseUrl: '',
    model: 'default',
    note: 'Azure Speech endpoints are resource and region specific.',
  },
  {
    value: 'cartesia',
    label: 'Cartesia',
    status: 'inventory',
    baseUrl: 'https://api.cartesia.ai',
    model: 'ink-whisper',
  },
  {
    value: 'elevenlabs',
    label: 'ElevenLabs Scribe',
    status: 'inventory',
    baseUrl: 'https://api.elevenlabs.io/v1',
    model: 'scribe_v1',
  },
  {
    value: 'google',
    label: 'Google Cloud STT',
    status: 'inventory',
    baseUrl: 'https://speech.googleapis.com/v1',
    model: 'latest_long',
  },
  {
    value: 'groq',
    label: 'Groq Whisper',
    status: 'inventory',
    baseUrl: 'https://api.groq.com/openai/v1',
    model: 'whisper-large-v3-turbo',
  },
  {
    value: 'mistral',
    label: 'Mistral Voxtral',
    status: 'inventory',
    baseUrl: 'https://api.mistral.ai/v1',
    model: 'voxtral-mini-latest',
  },
  {
    value: 'speechmatics',
    label: 'Speechmatics',
    status: 'inventory',
    baseUrl: 'https://asr.api.speechmatics.com/v2',
    model: 'default',
  },
  {
    value: 'soniox',
    label: 'Soniox',
    status: 'inventory',
    baseUrl: 'https://api.soniox.com/v1',
    model: 'stt-rt-preview',
  },
  {
    value: 'xai',
    label: 'xAI',
    status: 'inventory',
    baseUrl: 'https://api.x.ai/v1',
    model: 'whisper-1',
  },
]

export const REALTIME_PROVIDER_PRESETS: VoiceProviderPreset[] = [
  {
    value: 'openai',
    label: 'OpenAI Realtime',
    status: 'runtime',
    baseUrl: 'https://api.openai.com/v1/realtime/calls',
    model: 'gpt-realtime-2.1',
    realtimeVoice: 'marin',
    realtimeTranscriptionModel: 'gpt-realtime-whisper',
  },
  {
    value: 'volcengine.doubao_realtime',
    label: 'Volcengine Doubao Realtime',
    status: 'runtime',
    baseUrl: 'wss://openspeech.bytedance.com/api/v3/duplex/realtime/dialogue',
    model: '1.2.6.0',
    realtimeVoice: 'your-volcengine-voice',
    note: 'Wired through the backend Volcengine Doubao realtime runtime; requires a Realtime API key.',
  },
  {
    value: 'aws.nova_sonic',
    label: 'AWS Nova Sonic',
    status: 'inventory',
    baseUrl: '',
    model: 'amazon.nova-sonic-v1:0',
    note: 'Requires AWS region and Nova Sonic adapter wiring.',
  },
  {
    value: 'azure.realtime',
    label: 'Azure Realtime',
    status: 'inventory',
    baseUrl: '',
    model: 'gpt-realtime-2.1',
    note: 'Azure realtime endpoints are resource and deployment specific.',
  },
  {
    value: 'google.gemini_live',
    label: 'Google Gemini Live',
    status: 'inventory',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    model: 'gemini-live-2.5-flash-preview',
  },
  {
    value: 'google.gemini_live.vertex',
    label: 'Vertex Gemini Live',
    status: 'inventory',
    baseUrl: '',
    model: 'gemini-live-2.5-flash-preview',
    note: 'Vertex endpoints depend on project and region.',
  },
  {
    value: 'grok.realtime',
    label: 'Grok Realtime',
    status: 'inventory',
    baseUrl: 'https://api.x.ai/v1',
    model: 'grok-realtime',
  },
  {
    value: 'inworld.realtime',
    label: 'Inworld Realtime',
    status: 'inventory',
    baseUrl: 'https://api.inworld.ai',
    model: 'inworld-realtime',
  },
  {
    value: 'ultravox.realtime',
    label: 'Ultravox Realtime',
    status: 'inventory',
    baseUrl: 'https://api.ultravox.ai/api/',
    model: 'fixie-ai/ultravox',
    note: 'Requires Ultravox realtime adapter wiring.',
  },
  {
    value: 'xai.realtime',
    label: 'xAI Realtime',
    status: 'inventory',
    baseUrl: 'https://api.x.ai/v1',
    model: 'grok-realtime',
  },
]

const PRESETS_BY_CHANNEL: Record<VoiceProviderChannel, VoiceProviderPreset[]> = {
  llm: LLM_PROVIDER_PRESETS,
  stt: STT_PROVIDER_PRESETS,
  tts: TTS_PROVIDER_PRESETS,
  realtime: REALTIME_PROVIDER_PRESETS,
}

export function providerPresetByValue(
  channel: VoiceProviderChannel,
  value: string | null | undefined,
): VoiceProviderPreset | null {
  if (!value) return null
  return PRESETS_BY_CHANNEL[channel].find((preset) => preset.value === value) ?? null
}

export function providerPresetValues(channel: VoiceProviderChannel): string[] {
  return PRESETS_BY_CHANNEL[channel].map((preset) => preset.value)
}
