import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { test } from 'node:test'

function readSource(relativePath) {
  return fs.readFileSync(path.resolve(relativePath), 'utf8')
}

test('TrainingStudioPage uses direct page tabs with text-only labels and collapsed parameters', () => {
  const source = readSource('src/pages/TrainingStudioPage.tsx')
  const css = readSource('src/pages/TrainingStudioPage.css')
  const tabsPanelIndex = source.indexOf('className="training-studio-tabs-panel"')
  const trainingPanelIndex = source.indexOf('className="training-studio-training-panel"')
  const parametersOpenIndex = source.indexOf('parametersOpen &&')
  const parametersIndex = source.indexOf('className="training-studio-parameters-panel"')
  const battlePanelIndex = source.indexOf('className="training-studio-battle-panel"')
  const parameterToggleIndex = source.indexOf('className="training-studio-parameters-toggle"')
  const inlineConfigIndex = source.indexOf('className="training-studio-config-inline"')
  const trainingActionsIndex = source.indexOf('className="training-studio-training-actions"')
  const modePanelIndex = source.indexOf('className="training-studio-mode-panel"')
  const feedbackPanelIndex = source.indexOf('className="training-studio-feedback-panel"')
  const goalIndex = source.indexOf('className="training-studio-goal"')
  const startStepsIndex = source.indexOf('className="training-studio-start-steps"')
  const startButtonIndex = source.indexOf('onClick={startQuickSession}')
  const launcherIndex = source.indexOf('<TrainingStudioLauncher')

  assert.match(source, /type StudioTab = 'training' \| 'battle'/)
  assert.match(source, /activeTab, setActiveTab\] = useState<StudioTab>\('training'\)/)
  assert.match(source, /battlePrepStep, setBattlePrepStep\] = useState<1 \| 2>\(1\)/)
  assert.match(source, /parametersOpen, setParametersOpen\] = useState\(false\)/)
  assert.match(source, /trainingConfigSummary = useMemo/)
  assert.doesNotMatch(source, /Advanced training configuration/)
  assert.match(source, /className="training-studio-page-tabs"/)
  assert.match(source, /value=\{activeTab\}/)
  assert.match(source, /value: 'training',\s*ariaLabel: t\('training\.launch\.quickStart'\),\s*label: t\('training\.launch\.quickStart'\),/s)
  assert.match(source, /value: 'battle',\s*ariaLabel: t\('training\.launch\.prepareFirst'\),\s*label: t\('training\.launch\.prepareFirst'\),/s)
  assert.doesNotMatch(source, /<Wand2 size=\{14\}/)
  assert.doesNotMatch(source, /<ClipboardCheck size=\{14\}/)
  assert.match(source, /activeTab === 'training' \? \(/)
  assert.match(source, /className="training-studio-training-panel"/)
  assert.match(source, /className="training-studio-parameters-panel"/)
  assert.match(source, /className="training-studio-battle-panel"/)
  assert.match(source, /className="training-studio-action-stack"/)
  assert.match(source, /className="training-studio-start-steps"/)
  assert.match(source, /Quick start steps/)
  assert.match(source, /activeTab === 'battle' &&/)
  assert.match(source, /Preparation steps/)
  assert.match(source, /battlePrepStep === stepNumber/)
  assert.match(source, /battlePrepStep > stepNumber/)
  assert.match(source, /选择模式/)
  assert.match(source, /选择练法/)
  assert.match(source, /Describe Meeting/)
  assert.match(source, /Confirm opponent/)
  assert.match(source, /className="training-studio-parameters-toggle"/)
  assert.match(source, /aria-expanded=\{parametersOpen\}/)
  assert.match(source, /aria-controls="training-studio-parameters-panel"/)
  assert.match(source, /parametersOpen \? tr\([^)]*Hide training parameters[^)]*\) : tr\([^)]*Adjust training parameters/s)
  assert.match(source, /className="training-studio-config-inline"/)
  assert.match(source, /className="training-studio-training-actions"/)
  assert.match(source, /onClick=\{startQuickSession\}/)
  assert.match(source, /\{parametersOpen && \(\s*<section\s+id="training-studio-parameters-panel"[\s\S]*<TrainingStudioLauncher/s)
  assert.doesNotMatch(source, /className="training-studio-parameters-panel"[\s\S]*selectedModeLabel/)
  assert.doesNotMatch(source, /className="training-studio-parameters-panel"[\s\S]*trainingConfigSummary/)
  assert.doesNotMatch(source, /training-studio-parameters-head/)
  assert.match(source, /className="training-studio-battle-panel"[\s\S]*<BattlePrepFlow\s+embedded\s+onStepChange=\{setBattlePrepStep\}\s+onStudioConfigChange=\{setConfig\}\s+showSteps=\{false\}\s+studioConfig=\{config\}/s)
  assert.doesNotMatch(source, /type LaunchIntent/)
  assert.doesNotMatch(source, /launchIntent/)
  assert.doesNotMatch(source, /activeLaunch/)
  assert.doesNotMatch(source, /startGuidedBattle/)
  assert.doesNotMatch(source, /training\.launch\.editParameters/)
  assert.doesNotMatch(source, /trainingConfigOpen/)
  assert.doesNotMatch(source, /setTrainingConfigOpen/)
  assert.doesNotMatch(source, /<Dialog/)
  assert.doesNotMatch(source, /className="training-studio-config-toggle"/)
  assert.doesNotMatch(source, /aria-controls="training-studio-config-options"/)
  assert.notEqual(tabsPanelIndex, -1)
  assert.notEqual(trainingPanelIndex, -1)
  assert.notEqual(parametersOpenIndex, -1)
  assert.notEqual(parametersIndex, -1)
  assert.notEqual(battlePanelIndex, -1)
  assert.notEqual(parameterToggleIndex, -1)
  assert.notEqual(inlineConfigIndex, -1)
  assert.notEqual(trainingActionsIndex, -1)
  assert.notEqual(modePanelIndex, -1)
  assert.notEqual(feedbackPanelIndex, -1)
  assert.notEqual(goalIndex, -1)
  assert.notEqual(startStepsIndex, -1)
  assert.notEqual(startButtonIndex, -1)
  assert.notEqual(launcherIndex, -1)
  assert.ok(tabsPanelIndex < startStepsIndex)
  assert.ok(startStepsIndex < trainingPanelIndex)
  assert.ok(trainingPanelIndex < trainingActionsIndex)
  assert.ok(trainingActionsIndex < startButtonIndex)
  assert.ok(startButtonIndex < parameterToggleIndex)
  assert.ok(trainingActionsIndex < parameterToggleIndex)
  assert.ok(trainingActionsIndex < modePanelIndex)
  assert.ok(parametersIndex < modePanelIndex)
  assert.ok(modePanelIndex < feedbackPanelIndex)
  assert.ok(feedbackPanelIndex < goalIndex)
  assert.ok(parameterToggleIndex < parametersOpenIndex)
  assert.ok(parametersOpenIndex < parametersIndex)
  assert.ok(trainingActionsIndex < parametersIndex)
  assert.ok(parametersIndex < inlineConfigIndex)
  assert.ok(inlineConfigIndex < launcherIndex)
  assert.match(css, /\.training-studio-tabs-panel/)
  assert.match(css, /\.training-studio-page-tabs\.ui-segmented-control/)
  assert.match(css, /\.training-studio-tabs-panel\s*\{[\s\S]*order: 1;[\s\S]*align-items: center;[\s\S]*justify-content: space-between;/)
  assert.match(css, /\.training-studio-page-tabs\.ui-segmented-control\s*\{[\s\S]*width: fit-content;/)
  assert.doesNotMatch(css, /\.training-studio-page-tabs\.ui-segmented-control\s*\{[\s\S]*min-width: 260px;/)
  assert.match(css, /\.training-studio-page-tabs \.ui-segmented-control-button\[data-state='on'\]\s*\{[\s\S]*color: var\(--training-workbench-primary\);/)
  assert.match(css, /\.training-studio-training-panel\s*\{[\s\S]*order: 2;/)
  assert.match(css, /\.training-studio-battle-panel\s*\{[\s\S]*order: 2;[\s\S]*--amber: var\(--training-workbench-primary\);[\s\S]*--amber-soft: var\(--training-workbench-primary-soft\);/)
  assert.match(css, /\.training-studio-training-actions\s*\{[\s\S]*order: 1;/)
  assert.match(css, /\.training-studio-parameters-panel\s*\{[\s\S]*order: 2;/)
  assert.match(css, /\.training-studio-error\s*\{[\s\S]*order: 3;/)
  assert.match(css, /\.training-studio-mode-panel\s*\{[\s\S]*order: 4;/)
  assert.match(css, /\.training-studio-feedback-panel\s*\{[\s\S]*order: 5;/)
  assert.match(css, /\.training-studio-grid\s*\{[\s\S]*order: 6;/)
  assert.match(css, /\.training-studio-training-actions/)
  assert.match(css, /\.training-studio-training-actions\s*\{[\s\S]*grid-template-columns: minmax\(0, 1fr\) minmax\(320px, 380px\);/)
  assert.doesNotMatch(css, /\.training-studio-training-actions\s*\{[\s\S]*max-width: 940px;/)
  assert.doesNotMatch(css, /\.training-studio-parameters-panel\s*\{[\s\S]*max-width: 940px;/)
  assert.match(css, /\.training-studio-action-stack\s*\{[\s\S]*grid-template-columns: minmax\(0, 1fr\) minmax\(0, 1fr\);/)
  assert.match(css, /@media \(max-width: 767px\)[\s\S]*\.training-studio-action-stack\s*\{[\s\S]*min-width: 0;/)
  assert.match(css, /\.training-studio-start-steps\s*\{[\s\S]*order: 0;[\s\S]*justify-content: flex-end;/)
  assert.match(css, /\.training-studio-start-step-dot\s*\{[\s\S]*width: 26px;[\s\S]*height: 26px;/)
  assert.match(css, /\.training-studio-start-step-dot\.done/)
  assert.match(css, /\.training-studio-start-step-dot\.active/)
  assert.match(css, /\.training-studio-start-step-label\.active/)
  assert.match(css, /\.training-studio-start-step-line/)
  assert.match(css, /\.training-studio-start-step-line\.done/)
  assert.match(css, /\.training-studio-parameters-toggle\.ui-button/)
  assert.match(css, /\.training-studio-parameters-toggle-chevron\.open/)
  assert.match(css, /\.training-studio-parameters-panel/)
  assert.match(css, /\.training-studio-config-inline/)
  assert.doesNotMatch(css, /\.training-studio-parameters-head/)
  assert.doesNotMatch(css, /\.training-studio-launch-/)
  assert.doesNotMatch(css, /grid-template-columns: repeat\(3, minmax\(124px, 1fr\)\)/)
  assert.doesNotMatch(css, /\.training-studio-summary-edit\.ui-button/)
  assert.doesNotMatch(css, /\.training-studio-config-dialog/)
  assert.doesNotMatch(css, /\.training-studio-config-panel/)
  assert.doesNotMatch(css, /\.training-studio-config-toggle\.ui-button/)
})

test('TrainingStudioPage embeds battle prep as the second page tab', () => {
  const source = readSource('src/pages/TrainingStudioPage.tsx')
  const battlePrepSource = readSource('src/pages/BattlePrepPage.tsx')
  const battlePrepCss = readSource('src/pages/BattlePrepPage.css')

  assert.match(source, /import \{ BattlePrepFlow \} from '\.\/BattlePrepPage'/)
  assert.match(source, /className="training-studio-battle-panel"[\s\S]*<BattlePrepFlow\s+embedded\s+onStepChange=\{setBattlePrepStep\}\s+onStudioConfigChange=\{setConfig\}\s+showSteps=\{false\}\s+studioConfig=\{config\}/s)
  assert.doesNotMatch(source, /navigate\(APP_ROUTES\.practiceBattle/)
  assert.match(battlePrepSource, /export function BattlePrepFlow/)
  assert.match(battlePrepSource, /embedded = false/)
  assert.match(battlePrepSource, /showSteps = true/)
  assert.match(battlePrepSource, /onStepChange\?\.\(step\)/)
  assert.match(battlePrepSource, /showHeaderHeading = !embedded \|\| Boolean\(backAction\)/)
  assert.match(battlePrepSource, /\{\(showHeaderHeading \|\| showSteps\) && \(/)
  assert.match(battlePrepSource, /\{showHeaderHeading && \(/)
  assert.match(battlePrepSource, /\{showSteps && \(/)
  assert.match(battlePrepSource, /\{!embedded && \(\s*<div className="bpp-title-row">[\s\S]*<Zap size=\{22\} className="bpp-title-icon" \/>/s)
  assert.match(battlePrepSource, /bpp-page--embedded/)
  assert.match(battlePrepSource, /value=\{studioConfig\}/)
  assert.match(battlePrepSource, /onChange=\{onStudioConfigChange\}/)
  assert.match(battlePrepCss, /\.bpp-page--embedded/)
  assert.match(battlePrepCss, /background: transparent/)
  assert.match(battlePrepCss, /\.bpp-page--embedded \.bpp-header\s*\{[\s\S]*justify-content: flex-end;/)
})

test('TrainingStudioPage starts preset counterpart sessions with a persisted opening message', () => {
  const source = readSource('src/pages/TrainingStudioPage.tsx')
  const presets = readSource('src/services/trainingStudio.ts')

  assert.match(source, /const openingMessage = !isLiveCoachMode && scenarioStakeholder/)
  assert.match(source, /content: t\(scenarioStakeholder\.openingKey\)/)
  assert.match(source, /source: 'training_studio_opening'/)
  assert.match(source, /opening_message: openingMessage/)
  assert.match(presets, /openingKey: 'training\.interviewScenario\.resumeDeepDive\.opening'/)
  assert.match(presets, /openingKey: 'training\.productScenario\.roadmap\.opening'/)
})

test('BattlePrepPage returns to training studio when launched from the workbench', () => {
  const source = readSource('src/pages/BattlePrepPage.tsx')

  assert.match(source, /useLocation/)
  assert.match(source, /routeState\.source === 'training-studio'/)
  assert.match(source, /routeState\.returnTo === APP_ROUTES\.practiceCustom/)
  assert.match(source, /navigate\(APP_ROUTES\.practiceCustom, \{\s*state: \{/s)
  assert.match(source, /trainingStudioConfig: studioConfig/)
  assert.match(source, /Back to training studio/)
  assert.match(source, /navigate\(APP_ROUTES\.practiceScenarios\)/)
})

test('Training studio route and page title use the same product name', () => {
  const source = readSource('src/i18n.tsx')

  assert.match(source, /'nav\.trainingStudio': 'Training Studio'/)
  assert.match(source, /'training\.page\.title': 'Training Studio'/)
  assert.match(source, /'nav\.trainingStudio': '\u8bad\u7ec3\u5de5\u4f5c\u53f0'/)
  assert.match(source, /'training\.page\.title': '\u8bad\u7ec3\u5de5\u4f5c\u53f0'/)
  assert.match(source, /'training\.launcher\.aria': '\u8bad\u7ec3\u53c2\u6570'/)
})
