export const APP_ROUTES = {
  workbench: '/',
  practice: '/practice',
  practiceScenarios: '/practice/scenarios',
  practiceCustom: '/practice/custom',
  practiceLiveCoach: '/practice/live-coach',
  practiceDefense: '/practice/defense-prep',
  practiceBattle: '/practice/battle-prep',
  conversations: '/conversations',
  conversation: (roomId: number | string) => `/conversations/${encodeURIComponent(String(roomId))}`,
  review: '/review',
  reviewSessions: '/review/sessions',
  reviewSession: (sessionId: number | string) => `/review/sessions/${encodeURIComponent(String(sessionId))}`,
  growth: '/growth',
  growthLeaderboard: '/growth/leaderboard',
  config: '/config',
  configScenarios: '/config/scenarios',
  configPersonaNew: '/config/personas/new',
  configPersonaEdit: (personaId: number | string) => `/config/personas/${encodeURIComponent(String(personaId))}/edit`,
} as const
